=== fernandezortaalex/Tarea/Tarea_Lenguaje_de_marca/Tema1/repaso/ejercicios-xsd-xml/ejercicio9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hospital">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="departamento" minOccurs="2" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="xs:string"/>
                                    <xs:element name="medicojefe">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-Z][a-z]+ [A-Z][a-z]+"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="paciente" minOccurs="2" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="dni">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:pattern value="\d{8}[A-Z]"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="edad">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="0"/>
                                                            <xs:maxInclusive value="120"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="fechaIngreso" type="xs:date" />
                                                <xs:element name="diagnostico" type="xs:string" />
                                                <xs:element name="tratamiento" type="xs:string" />
                                                <xs:element name="proveedor" minOccurs="0"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
    </xs:element>
</xs:schema>

=== fernandezortaalex/Tarea/Tarea_Lenguaje_de_marca/Tema1/repaso/ejercicios-xsd-xml/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio9.xsd">

    <nombre>asdaw</nombre>
    <departamento>
        <nombre>adsad</nombre>
        <medicojefe>Aadas Fefsdf</medicojefe>
        <paciente>
            <dni>22334455N</dni>
            <edad>56</edad>
            <fechaIngreso>2005-11-24</fechaIngreso>
            <diagnostico>sfdsfsdf</diagnostico>
            <tratamiento>czsdc</tratamiento>
        </paciente>
        <paciente>
            <dni>22334455N</dni>
            <edad>56</edad>
            <fechaIngreso>2005-11-24</fechaIngreso>
            <diagnostico>sfdsfsdf</diagnostico>
            <tratamiento>czsdc</tratamiento>
        </paciente>
    </departamento>
    <departamento>
        <nombre>adsad</nombre>
        <medicojefe>Aadas Fefsdf</medicojefe>
        <paciente>
            <dni>22334455N</dni>
            <edad>56</edad>
            <fechaIngreso>2005-11-24</fechaIngreso>
            <diagnostico>sfdsfsdf</diagnostico>
            <tratamiento>czsdc</tratamiento>
        </paciente>
        <paciente>
            <dni>22334455N</dni>
            <edad>56</edad>
            <fechaIngreso>2005-11-24</fechaIngreso>
            <diagnostico>sfdsfsdf</diagnostico>
            <tratamiento>czsdc</tratamiento>
        </paciente>
    </departamento>
</hospital>
