<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso [
<!ELEMENT curso (nombre, alumno+)>
<!ELEMENT alumno (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
]>

<curso>
    <nombre>Bachillerato</nombre>
    <alumno>
        <nombre>Alex</nombre>
        <apellido>Fernandez</apellido>
    </alumno>

    <alumno>
        <nombre>Iker</nombre>
        <apellido>Jesus</apellido>
    </alumno>
</curso>